### ISSUE TITLE
If using Test::RedisServer with Redis 4.0.1, server ready state is never detected

### ISSUE THREAD

**Issue by robinsmidsrod** [typester/Test-RedisServer#6]
With version 4.0.1 of Redis server, the log line used to signify that the server is ready to accept connections is formatted like this: `18565:M 17 Aug 14:28:47.860 * Ready to accept connections`

In previous versions the log line was formatted like this: `33:M 17 Aug 14:39:07.985 * The server is now ready to accept connections on port 6379`

Please ensure the regexp in the `start` sub is changed to support both of these syntaxes. I would recommend you match on more generic terms or use a ping query to redis to verify it is operational instead.

This is using version 0.20 of Test::RedisServer.

**Comment by Songmu** [comment]
Thank you for your fix. I released new version as 0.21.
